### ISSUE TITLE
Fix issues mentioned in case study 1 presentation

### ISSUE THREAD

**Issue by johnwhoyou** [samueluy/CSSECDV-CS1#3]
Implement the fix for the issues mentioned by sir Keinaz during CS1 presentation

**Comment by johnwhoyou** [comment]
from @alyannaabalos :

- [ ] unable to clear fields after unsuccessful user registration
- [ ] unable to clear fields after pressing “back” during registration
- [ ] should block non-exisiting username after 5 attempts (disable log in)
- [ ] should also display success messages not only errors

**Comment by samueluy** [comment]
- [ ] sent code works even after one invalid attempt. The email code must only work once regardless of invalid or valid input

**Comment by samueluy** [comment]
> from @alyannaabalos :
> 
> * [ ]  should block non-exisiting username after 5 attempts (disable log in)

Will not implement using db na. Hashmap na lang gagawin ko dito since restart on program close naman + baka ma overload ung db
